<?php if ($this->tSearchEnabled()): ?>
    <script>
        document.getElementsByTagName('body')[0].classList.add('tagalys-search-enabled');

        onTagalysReady(function () {
            var selector = "<?php echo $this->getTagalysConfig('search_box_selector') ?>";
            var searchResultsURL = "<?php echo $this->getTsearchUrl(); ?>";
            // console.log("results: " + searchResultsURL);
            Tagalys.UIWidgets.SearchSuggestions.init(selector, {
                searchResultsURL: searchResultsURL,
                // templates: {
                //     widget: {
                //         options: {
                //             inheritAlignmentElementWidth: false
                //         }
                //     }
                // }
            })
        });

    </script>
    <style type="text/css">
        #tagalys-namespace .search-suggestions {
            z-index: 1000;
        }
    </style>
<?php endif; ?>
