<?php if ($this->tSearchEnabled()): ?>
    <script>
        document.getElementsByTagName('body')[0].classList.add('tagalys-search-enabled');

        onTagalysReady(function () {
            var selector = "<?php echo $this->getTagalysConfig('search_box_selector') ?>";
            var searchInputNode = document.querySelector(selector);
            if(!searchInputNode) return;

            var searchResultsURL = "<?php echo $this->getTsearchUrl(); ?>";
            var alignToSelector = "<?php echo $this->getTagalysConfig('suggestions_align_to_selector'); ?>";
            if(!alignToSelector) {
                alignToSelector = false;
            }

            Tagalys.UIWidgets.SearchSuggestions.init(selector, {
                searchResultsURL: searchResultsURL,
                templates: {
                    widget: {
                        options: {
                            alignToSelector: alignToSelector,
                            // inheritAlignmentElementWidth: false
                        }
                    }
                }
            })

            // Temp fix for form submit
            var nearestFormNode = searchInputNode.closest("form");
            if(nearestFormNode) {
                nearestFormNode.setAttribute("action", searchResultsURL);
            }
        });

    </script>
<?php endif; ?>
